include ../../common/Makefile

DEFS =-DSFML_STATIC
INC_DIR =../../common/includes/

LINKER_FLAGS=-l sfml-graphics-s -l sfml-window-s -l sfml-system-s  -l gdi32 -l winmm -l opengl32
LIB_DIR =../../common/libs/SFML/
